const COLORS = {
  core: "#c7d6ff",
  about: "#7ea6ff",
  experience: "#a99bff",
  projects: "#e59cc0",
  skills: "#6fcfb0",
  github: "#d8b66a",
  linkedin: "#6aa9ff",
};

const RAW_NODES = [
  {
    id: "core",
    label: "Hiten Gupta",
    kind: "core",
    panel: "about",
    color: COLORS.core,
    size: 0.5,
    position: [0, 0, 0],
    hint: "Summary, education and achievements",
  },
  {
    id: "about",
    label: "About",
    kind: "section",
    panel: "about",
    color: COLORS.about,
    size: 0.28,
    position: [-3.1, 1.5, 0.7],
    hint: "Who I am and what I build",
  },
  {
    id: "education",
    label: "Education",
    kind: "satellite",
    panel: "about",
    focus: "education",
    color: COLORS.about,
    size: 0.13,
    position: [-4.4, 2.4, 1.5],
    hint: "BSc (Hons) Computer Science, University of Delhi",
  },
  {
    id: "achievements",
    label: "Achievements",
    kind: "satellite",
    panel: "about",
    focus: "achievements",
    color: COLORS.about,
    size: 0.13,
    position: [-3.5, 3.0, -0.7],
    hint: "Hackathon finals and production deployments",
  },
  {
    id: "experience",
    label: "Experience",
    kind: "section",
    panel: "experience",
    color: COLORS.experience,
    size: 0.28,
    position: [3.0, 1.8, -0.4],
    hint: "Internship, freelance work and society leadership",
  },
  {
    id: "hiverift",
    label: "HiveRift",
    kind: "satellite",
    panel: "experience",
    focus: "hiverift",
    color: COLORS.experience,
    size: 0.13,
    position: [5.0, 2.0, -1.7],
    hint: "Data Analyst Intern, Apr – Jul 2026",
  },
  {
    id: "freelance",
    label: "Freelance ML",
    kind: "satellite",
    panel: "experience",
    focus: "freelance",
    color: COLORS.experience,
    size: 0.13,
    position: [3.6, 3.2, 0.6],
    hint: "Predictive analytics and forecasting models",
  },
  {
    id: "leadership",
    label: "Techathon",
    kind: "satellite",
    panel: "experience",
    focus: "techathon",
    color: COLORS.experience,
    size: 0.13,
    position: [1.9, 3.1, -1.9],
    hint: "President, Techathon Society",
  },
  {
    id: "projects",
    label: "Projects",
    kind: "section",
    panel: "projects",
    color: COLORS.projects,
    size: 0.28,
    position: [2.8, -1.8, 1.2],
    hint: "GenHive and Hive Search Bot, both live",
  },
  {
    id: "hive-search",
    label: "Hive Search",
    kind: "project",
    panel: "project",
    projectId: "hive-search",
    color: "#e88aa6",
    size: 0.16,
    position: [4.4, -0.9, 2.1],
    hint: "Conversational search built in Next.js",
  },
  {
    id: "genhive",
    label: "GenHive",
    kind: "project",
    panel: "project",
    projectId: "genhive",
    color: "#d89be0",
    size: 0.16,
    position: [4.6, -2.8, 0.5],
    hint: "AI sales assistant for lead qualification",
  },
  {
    id: "skills",
    label: "Skills",
    kind: "section",
    panel: "skills",
    color: COLORS.skills,
    size: 0.28,
    position: [-2.9, -1.9, -1.1],
    hint: "Python, LLMs, NLP, data and backend tooling",
  },
  {
    id: "skill-lang",
    label: "Languages",
    kind: "satellite",
    panel: "skills",
    focus: "lang",
    color: COLORS.skills,
    size: 0.13,
    position: [-4.4, -0.9, -1.9],
    hint: "Python, SQL, TypeScript",
  },
  {
    id: "skill-ml",
    label: "AI / ML",
    kind: "satellite",
    panel: "skills",
    focus: "ml",
    color: COLORS.skills,
    size: 0.13,
    position: [-4.7, -2.3, -0.5],
    hint: "Scikit-learn, TensorFlow, LangChain, LLMs",
  },
  {
    id: "skill-data",
    label: "Data",
    kind: "satellite",
    panel: "skills",
    focus: "data",
    color: COLORS.skills,
    size: 0.13,
    position: [-3.7, -3.6, -0.2],
    hint: "Pandas, NumPy, Scrapy, ETL pipelines",
  },
  {
    id: "skill-tools",
    label: "Tools",
    kind: "satellite",
    panel: "skills",
    focus: "tools",
    color: COLORS.skills,
    size: 0.13,
    position: [-2.3, -3.4, -2.3],
    hint: "FastAPI, Next.js, Docker, GitHub Actions",
  },
  {
    id: "github",
    label: "GitHub",
    kind: "external",
    panel: "github",
    color: COLORS.github,
    size: 0.24,
    position: [0.4, 3.6, -2.1],
    hint: "Repositories and recent activity",
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    kind: "external",
    panel: "linkedin",
    color: COLORS.linkedin,
    size: 0.24,
    position: [-1.0, -3.4, 2.4],
    hint: "Professional profile",
  },
];

const PARENT_BY_PANEL = {
  about: "about",
  experience: "experience",
  project: "projects",
  skills: "skills",
};

export const NODES = RAW_NODES.map((node, index) => ({
  ...node,
  parent: node.kind === "satellite" || node.kind === "project" ? PARENT_BY_PANEL[node.panel] : null,
  phase: index * 1.618,
}));

export const NODE_MAP = Object.fromEntries(NODES.map((node) => [node.id, node]));

export const EDGES = [
  ["core", "about"],
  ["core", "experience"],
  ["core", "projects"],
  ["core", "skills"],
  ["core", "github"],
  ["core", "linkedin"],
  ["about", "experience"],
  ["experience", "projects"],
  ["projects", "skills"],
  ["skills", "about"],
  ["github", "projects"],
  ["github", "experience"],
  ["linkedin", "about"],
  ["linkedin", "experience"],
  ["about", "education"],
  ["about", "achievements"],
  ["experience", "hiverift"],
  ["experience", "freelance"],
  ["experience", "leadership"],
  ["hiverift", "hive-search"],
  ["hiverift", "genhive"],
  ["projects", "hive-search"],
  ["projects", "genhive"],
  ["hive-search", "genhive"],
  ["skills", "skill-lang"],
  ["skills", "skill-ml"],
  ["skills", "skill-data"],
  ["skills", "skill-tools"],
  ["skill-lang", "hive-search"],
  ["skill-ml", "genhive"],
  ["skill-tools", "genhive"],
  ["skill-tools", "hive-search"],
  ["skill-data", "hiverift"],
  ["skill-ml", "freelance"],
  ["achievements", "hive-search"],
  ["achievements", "genhive"],
  ["leadership", "achievements"],
];

const ADJACENCY = EDGES.reduce((map, [source, target]) => {
  if (!map.has(source)) map.set(source, new Set());
  if (!map.has(target)) map.set(target, new Set());
  map.get(source).add(target);
  map.get(target).add(source);
  return map;
}, new Map());

export function getRelatedIds(activeId) {
  if (!activeId || !NODE_MAP[activeId]) return null;
  const related = new Set([activeId]);
  const neighbors = ADJACENCY.get(activeId);
  if (neighbors) neighbors.forEach((id) => related.add(id));
  return related;
}

export const PRIMARY_NAV = ["about", "experience", "projects", "skills", "github", "linkedin"];

export const FRAMING = { vertical: 4.9, horizontal: 5.6 };
