const COLORS = {
  core: "#7dd3fc",
  about: "#22d3ee",
  experience: "#a78bfa",
  projects: "#f472b6",
  skills: "#34d399",
  github: "#fbbf24",
  linkedin: "#60a5fa",
};

const RAW_NODES = [
  {
    id: "core",
    label: "Hiten Gupta",
    kind: "core",
    panel: "about",
    color: COLORS.core,
    size: 0.5,
    position: [0, 0, 0],
    hint: "Profile core: summary, education and achievements",
  },
  {
    id: "about",
    label: "About",
    kind: "section",
    panel: "about",
    color: COLORS.about,
    size: 0.28,
    position: [-3.1, 1.5, 0.7],
    hint: "Who I am and what I build",
  },
  {
    id: "education",
    label: "Education",
    kind: "satellite",
    panel: "about",
    focus: "education",
    color: COLORS.about,
    size: 0.13,
    position: [-4.4, 2.4, 1.5],
    hint: "BSc (Hons) Computer Science, University of Delhi",
  },
  {
    id: "achievements",
    label: "Achievements",
    kind: "satellite",
    panel: "about",
    focus: "achievements",
    color: COLORS.about,
    size: 0.13,
    position: [-3.5, 3.0, -0.7],
    hint: "Hackathon podiums and production deployments",
  },
  {
    id: "experience",
    label: "Experience",
    kind: "section",
    panel: "experience",
    color: COLORS.experience,
    size: 0.28,
    position: [3.0, 1.8, -0.4],
    hint: "Internship and freelance ML engineering",
  },
  {
    id: "hiverift",
    label: "HiveRift",
    kind: "satellite",
    panel: "experience",
    focus: "hiverift",
    color: COLORS.experience,
    size: 0.13,
    position: [4.5, 2.6, -1.5],
    hint: "Data Analyst Intern at HiveRift Software",
  },
  {
    id: "freelance",
    label: "Freelance ML",
    kind: "satellite",
    panel: "experience",
    focus: "freelance",
    color: COLORS.experience,
    size: 0.13,
    position: [3.6, 3.2, 0.6],
    hint: "Project-based machine learning engineering",
  },
  {
    id: "projects",
    label: "Projects",
    kind: "section",
    panel: "projects",
    color: COLORS.projects,
    size: 0.28,
    position: [2.8, -1.8, 1.2],
    hint: "Chatbots, data pipelines and predictive models",
  },
  {
    id: "search-chatbot",
    label: "Search Bot",
    kind: "project",
    panel: "project",
    projectId: "search-chatbot",
    color: "#fb7185",
    size: 0.16,
    position: [4.4, -0.9, 2.1],
    hint: "Natural language product discovery",
  },
  {
    id: "sales-chatbot",
    label: "Sales Bot",
    kind: "project",
    panel: "project",
    projectId: "sales-chatbot",
    color: "#f472b6",
    size: 0.16,
    position: [4.6, -2.8, 0.5],
    hint: "Lead qualification and follow-ups",
  },
  {
    id: "data-pipeline",
    label: "Data Pipeline",
    kind: "project",
    panel: "project",
    projectId: "data-pipeline",
    color: "#e879f9",
    size: 0.16,
    position: [2.7, -3.5, 2.5],
    hint: "Millions of records scraped and cleaned",
  },
  {
    id: "predictive-ml",
    label: "Forecasting ML",
    kind: "project",
    panel: "project",
    projectId: "predictive-ml",
    color: "#f0abfc",
    size: 0.16,
    position: [1.3, -2.6, 3.0],
    hint: "Supervised and unsupervised forecasting models",
  },
  {
    id: "skills",
    label: "Skills",
    kind: "section",
    panel: "skills",
    color: COLORS.skills,
    size: 0.28,
    position: [-2.9, -1.9, -1.1],
    hint: "Python, ML, NLP, data engineering and analytics",
  },
  {
    id: "skill-ml",
    label: "ML & AI",
    kind: "satellite",
    panel: "skills",
    focus: "ml",
    color: COLORS.skills,
    size: 0.13,
    position: [-4.4, -1.0, -1.9],
    hint: "Scikit-learn, TensorFlow, LangChain, LLMs",
  },
  {
    id: "skill-data",
    label: "Data Eng",
    kind: "satellite",
    panel: "skills",
    focus: "data",
    color: COLORS.skills,
    size: 0.13,
    position: [-4.1, -3.1, -0.3],
    hint: "Pandas, NumPy, ETL pipelines",
  },
  {
    id: "skill-analytics",
    label: "Analytics",
    kind: "satellite",
    panel: "skills",
    focus: "analytics",
    color: COLORS.skills,
    size: 0.13,
    position: [-2.3, -3.4, -2.3],
    hint: "EDA, statistical modelling, Power BI",
  },
  {
    id: "github",
    label: "GitHub",
    kind: "external",
    panel: "github",
    color: COLORS.github,
    size: 0.24,
    position: [0.4, 3.6, -2.1],
    hint: "Live repositories and commit pipeline",
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    kind: "external",
    panel: "linkedin",
    color: COLORS.linkedin,
    size: 0.24,
    position: [-1.0, -3.4, 2.4],
    hint: "Professional profile and network",
  },
];

const PARENT_BY_PANEL = {
  about: "about",
  experience: "experience",
  project: "projects",
  skills: "skills",
};

export const NODES = RAW_NODES.map((node, index) => ({
  ...node,
  parent: node.kind === "satellite" || node.kind === "project" ? PARENT_BY_PANEL[node.panel] : null,
  phase: index * 1.618,
}));

export const NODE_MAP = Object.fromEntries(NODES.map((node) => [node.id, node]));

export const EDGES = [
  ["core", "about"],
  ["core", "experience"],
  ["core", "projects"],
  ["core", "skills"],
  ["core", "github"],
  ["core", "linkedin"],
  ["about", "experience"],
  ["experience", "projects"],
  ["projects", "skills"],
  ["skills", "about"],
  ["github", "projects"],
  ["github", "experience"],
  ["linkedin", "about"],
  ["linkedin", "experience"],
  ["about", "education"],
  ["about", "achievements"],
  ["experience", "hiverift"],
  ["experience", "freelance"],
  ["hiverift", "search-chatbot"],
  ["hiverift", "sales-chatbot"],
  ["hiverift", "data-pipeline"],
  ["freelance", "predictive-ml"],
  ["projects", "search-chatbot"],
  ["projects", "sales-chatbot"],
  ["projects", "data-pipeline"],
  ["projects", "predictive-ml"],
  ["search-chatbot", "sales-chatbot"],
  ["skills", "skill-ml"],
  ["skills", "skill-data"],
  ["skills", "skill-analytics"],
  ["skill-ml", "predictive-ml"],
  ["skill-ml", "search-chatbot"],
  ["skill-data", "data-pipeline"],
  ["skill-analytics", "data-pipeline"],
  ["achievements", "search-chatbot"],
  ["achievements", "sales-chatbot"],
];

const ADJACENCY = EDGES.reduce((map, [source, target]) => {
  if (!map.has(source)) map.set(source, new Set());
  if (!map.has(target)) map.set(target, new Set());
  map.get(source).add(target);
  map.get(target).add(source);
  return map;
}, new Map());

export function getRelatedIds(activeId) {
  if (!activeId || !NODE_MAP[activeId]) return null;
  const related = new Set([activeId]);
  const neighbors = ADJACENCY.get(activeId);
  if (neighbors) neighbors.forEach((id) => related.add(id));
  return related;
}

export const PRIMARY_NAV = ["about", "experience", "projects", "skills", "github", "linkedin"];

export const FRAMING = { vertical: 4.9, horizontal: 5.6 };
